dist: xenial
language: python
python:
- 3.6
- 3.7
cache:
- pip
- apt
install:
- cd python
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
- $HOME/.poetry/bin/poetry install
- $HOME/.poetry/bin/poetry run pip list
script:
- $HOME/.poetry/bin/poetry run pytest -vv --cov=src --cov-report xml tests
after_script:
- pip install codacy-coverage
- python-codacy-coverage -r coverage.xml
before_deploy:
- $HOME/.poetry/bin/poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- $HOME/.poetry/bin/poetry build
deploy:
  provider: script
  script: "$HOME/.poetry/bin/poetry publish"
  skip_cleanup: true
  on:
    python: 3.7
    repo: uc-cdis/gen3authz
    tags: true
after_deploy:
- pip install gen3git
- gen3git release
env:
  global:
  - secure: YpbDAuLAkH+O+PRiLTd/DioGDWssLmNIOhhk4bWyhvX3B8sSB6wkiWEQg2SHAqFR08f8/oI/i8H47sajo4CZokrpQlmH80iV58kprn2tfH2zyIpdNot0EexZ0uZDvuGvY6Vzxd81YoWZxF4Ugl37npNrM+EzgkTxqd/63pcUYfPXgwdIxtf4gvBUR5WcrF+j+sWLnRCKk/6iB5Q/lmDLXWMTmPYahgAdPChrbSVD9G6vRnI7aQtkYstsVhmSRz3G6UqCzgFOYcPic3PpeUvULJCDgClabFtbgauzANZQBnPdV3vS2b49QwMf1Z2UfLVUrRNmypmpM4iukaBXkvQ/7hHJyiQvtfXsIvT6udFBMT3U/4CDKmYNIlDiBcP3UFird6wFo135FYEhyDHZTNJwsx4IlLosUG5Ep3gHZJ7IJwbCmMaIBt8W2gRHFN4worNmCxKBX5Ew5S3e/nilcUyYNaEFBSEp6mzaIOKuMC5yQuSuzsa4oCmkPRBZkvOnnhvU0SdNjvRTbmX64koxb3awL7M1YeAlp6osxrFppNxoXcjLuPdLVGLQGnETtxi5GZkmfrnIU/BoM2D/MMIvwRXn5OUofV2OgCrQPUUvsZf/zQk7QKJ53z4p4CpuAgZ8Qk3bw5DI4rJU655tkR88dvZgCrtJ5KkhteeyzNdWGM6OBng=
  - secure: QgrUcEsQHo0Q4HX/ykfhfApu7XbZHzVHybhEQw2Y/upg38VghNIl4Gv1e1s/ErkLddENGZdMUWAr5mAVuQGrob1ILQv0QW4btouiaJo80gdW3LjPNGSZd80xwY96ZSoLhP9JATMCBXUXy3NMd66d9S1uRdH1z8JTZ8qI4PBPIrWziz9givbXZcjMlcb6qHtyxjLBwmdwkwJ8TA187a6MAC0zGi2XJVbhQpwDcZBBGhH8WBum1QasPSVTDViCPWWJhlSiV2ihnH+eWcJK1VlBqaykqfZEf5/ksHLzJtS/h8aEbuAU+gHAsLT4fpV1m4sBmxEuHw8SRLwaUuP0CB29EzWCD/klfDp5TD8VLUs5hYyTDPRPPPCLTFbdqJE3oIGTu+GRqoFIOGxH5Ysg4kPAm/2ts7FWB5G3f6nkriG1SQZnw8KdvhKpEEVojw5TtNW1yTqLaitQXRMK/dPnl3FVJ75THvPZKBy75ZnZ0DyFACpnPQPZF7KCNh50IJA1rGuTVtxRuwhbZ6PJET689x9a27aHHY+CEWdhITUpBg2Uhbw2XrRCZnvIKY/ylxTO9ZVzLbTa96TsRcVhDLXkVe7LKCMPamyaa/oiu5oT9c7i3BR35IiHj+aXIG4LFDL7XrqpWpffZ7prLTl6t1k8O7BifUJ5qu7PXtswFYIoar79eGc=
  - secure: MkMVFL6tXTgWcQjV1mpndf47bI+fhHDf9tVzr8UeMeJ0pkQ1jLyVmAnHe+Oj3BhciHFdyQJ5o/IKS6Ynz6PSZV/e3wDD9afgb3gw7fj0AbI0klnDGoE1kSdGWzO042zKLituz3xZQ6iAWyHuWMS06fReF8ZOV81yK8pCoQxhY1/mZ3yulCtgi8rdlYo6QJx9txA9IJBZC77f/okUCSVd4pywvjn91CS65EkJ08MrlQipKG5ew2Ysg/ilR+ev8DyrJXWRbG28PEON7/Ld2zlHKLPx7OaPKxQqJvC2Cd2YPq5WHQmx461qgMdmnuZf/h1c8VWgVHCF/wlMLl7EVdGQT0FE4hGohe0GaPfysM3OJsFApHjmcxg6bTFlNNTQtcdBhWBgCSlS6Mro82/nIuo04yTOJgd0MBjDFQH6pnNTUFoYBqVpYdCz3t0hvj1rwUMBxpWfUVuUXaQ59CFCnuGHnSt58XJLne1ZIYjrDyrgUXCMvfZrAM4FFU6/7w7r+IQZW6FbGWZq2pdkVTio+M5g0j7ErskLQ9UwysuuEqqhRQKhmruy9Cj0IxoIljTs333NKauX7RKR35O8YX7Imr0GA8vPmO4jsIK7KfQMQ0fytuZ50tTXeUjnmAtO3lEg3dCv/C+LpFejDNGNYsZldehBTl0TdfJtcRt0/qVW8Sygxyg=
